let data = {
    "code": 200,
    "msg": "成功",
    "data": [{
        "id": -2,
        "name": "所有图片",
        "childs": [],
        "imgCount": "4",
        "pid": 0
    }, {
        "id": -2,
        "name": "未被分类",
        "childs": [],
        "imgCount": "1",
        "pid": 0
    }, {
        "id": "1",
        "name": "动漫",
        "pid": "0",
        "childs": [{
            "id": "3",
            "name": "火影忍者",
            "pid": "1",
            "imgCount": "0"
        }, {
            "id": "4",
            "name": "海贼王",
            "pid": "1",
            "imgCount": "0"
        }],
        "imgCount": "0"
    }, {
        "id": "14",
        "name": "动物世界",
        "pid": "0",
        "childs": [{
            "id": "15",
            "name": "猫猫",
            "pid": "14",
            "imgCount": "1"
        }, {
            "id": "16",
            "name": "狗狗",
            "pid": "14",
            "imgCount": "2"
        }, {
            "id": "17",
            "name": "老虎",
            "pid": "14",
            "childs": [{
                "id": "18",
                "name": "东北虎",
                "pid": "17",
                "imgCount": "0"
            }],
            "imgCount": "0"
        }, {
            "id": "19",
            "name": "狮子",
            "pid": "14",
            "imgCount": "0"
        }],
        "imgCount": "3"
    }, {
        "id": "20",
        "name": "新分类",
        "pid": "0",
        "imgCount": "0"
    }]
}