let data = {
    "data": {
        "type": 1,
        "id": 749,
        "name": "TPR法兰绒地垫24*17inch",
        "isOverSell": true,
        "tier": [{
            "ruleId": 3252,
            "productId": 749,
            "minQuantity": 1,
            "maxQuantity": 14,
            "discountType": 0,
            "discountValue": 100.0000
        }, {
            "ruleId": 3253,
            "productId": 749,
            "minQuantity": 15,
            "maxQuantity": 99,
            "discountType": 0,
            "discountValue": 98.0000
        }, {
            "ruleId": 3254,
            "productId": 749,
            "minQuantity": 100,
            "maxQuantity": 199,
            "discountType": 0,
            "discountValue": 97.0000
        }, {
            "ruleId": 3255,
            "productId": 749,
            "minQuantity": 200,
            "maxQuantity": 0,
            "discountType": 0,
            "discountValue": 95.0000
        }],
        "skuList": [{
            "inventory": 295,
            "itemDetailId": 11798,
            "sku": "11798",
            "materialCode": "JYI119J2147300100",
            "enabled": true,
            "mcpSku": "CIM-MKB4AH6K",
            "price": 20.60,
            "weight": 375,
            "decorationTechCode": "Sublimation",
            "size": {
                "value": "OneSize",
                "label": "均码"
            },
            "color": {
                "value": "White",
                "hex": "#FFFFFF",
                "values": ["#FFFFFF"],
                "label": "漂白"
            }
        }],
        "images": {
            "White": [{
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_1_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_1_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_1_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_2_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_2_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_2_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_3_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_3_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_3_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_4_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_4_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_4_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_5_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_5_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_5_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_6_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_6_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_6_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_7_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_7_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_7_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_8_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_8_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_8_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_9_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_9_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_9_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_10_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_10_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_10_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_11_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_11_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_11_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_12_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_12_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_12_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_13_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_13_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_13_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_14_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_14_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_14_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }, {
                "large": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_15_large.jpg",
                "normal": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_15_large.jpg?x-oss-process=image/resize,w_800/format,jpg",
                "thumbnail": "https://r1.depoga.com/productImage/DPJ/scene/JYI119J214730_1_15_large.jpg?x-oss-process=image/resize,w_100/format,jpg"
            }]
        },
        "techs": [{
            "value": "Sublimation",
            "valueDisplay": "热升华"
        }],
        "colors": ["White"],
        "productId": 749,
        "productName": "TPR法兰绒地垫24*17inch"
    },
    "success": true
}