var resData = {
    msg: "操作成功",
    code: 200,
    data: {
        list: [{
                id: 67,
                name: "asdf",
                enName: "87",
                aliasName: "8",
                listImageUrl: "group1/M00/00/39/wKhYI2BcKyWAKnszAAYi5Pu-tPA737.png",
                listImageThumbnailUrl: "group1/M00/00/39/wKhYI2BcKyWAD8QMAAIUw9sTeuQ815.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                            sizeId: 21,
                            sizeName: "L",
                        }, ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                            sizeId: 21,
                            sizeName: "L",
                        }, ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
            {
                id: 68,
                name: "抱枕",
                enName: "3",
                aliasName: "77",
                listImageUrl: "group1/M00/00/3A/wKhYI2BcMJeATq2HAAb3X8nr7sU647.png",
                listImageThumbnailUrl: "group1/M00/00/3A/wKhYI2BcMJeAMmsNAAC87Blbfx8530.jpg",
                colorSizeList: [{
                        colorTone: "#0000FF",
                        colorClassifyId: 100020,
                        colorEnName: "Blue",
                        colorName: "蓝色",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                    {
                        colorTone: "#FF0000",
                        colorClassifyId: 100021,
                        colorEnName: "Red",
                        colorName: "红",
                        sizeList: [{
                                sizeId: 21,
                                sizeName: "L",
                            },
                            {
                                sizeId: 22,
                                sizeName: "XL",
                            },
                        ],
                    },
                ],
            },
        ],
        nowPage: 1,
        total: 32,
    },
};